//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecomsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class laptop_model
    {
        public int laptop_id { get; set; }
        public int category_id { get; set; }
        public string laptop_name { get; set; }
        public string description { get; set; }
        public string imagepath { get; set; }
        public decimal laptop_price { get; set; }
    }
}
